'use client';

import { useMemo, useState } from 'react';
import { ArrowDownToLine, Banknote, CircleDollarSign, Clock3, Percent, ShoppingBag, WalletCards } from 'lucide-react';

const money = (value) => `$${Number(value || 0).toFixed(2)} MXN`;
const active = (item) => String(item.status || '').toLowerCase() !== 'cancelled';

function Metric({ label, value, detail, icon: Icon, color }) {
  return <div className="rounded-3xl border border-white/70 bg-white/90 p-5 shadow-xl shadow-slate-200/40"><div className="mb-4 flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">{label}</span><span className={`rounded-xl p-2.5 ${color}`}><Icon className="h-4 w-4" /></span></div><p className="text-2xl font-bold text-slate-800">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div>;
}

export default function SellerEarningsOverview({ report, orders, onDownload }) {
  const [period, setPeriod] = useState('all');
  const filteredOrders = useMemo(() => {
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    if (period === 'week') start.setDate(start.getDate() - 6);
    if (period === 'month') start.setDate(start.getDate() - 29);
    return orders.filter((order) => period === 'all' || new Date(order.created_at) >= start);
  }, [orders, period]);
  const products = useMemo(() => {
    const result = {};
    filteredOrders.forEach((order) => (order.items || []).filter(active).forEach((item) => {
      const key = item.product_id || item.product_name;
      if (!result[key]) result[key] = { key, name: item.product_name || 'Producto', units: 0, gross: 0 };
      result[key].units += Number(item.quantity || 1);
      result[key].gross += Number(item.subtotal || 0);
    }));
    return Object.values(result).map((product) => ({ ...product, net: product.gross * 0.85, fee: product.gross * 0.15 })).sort((a, b) => b.gross - a.gross);
  }, [filteredOrders]);
  const totals = report?.totals || {};
  const periodGross = products.reduce((sum, product) => sum + product.gross, 0);
  const gross = period === 'all' ? Number(totals.grossSales || periodGross) : periodGross;
  const net = period === 'all' ? Number(totals.sellerPayout || gross * 0.85) : gross * 0.85;
  const fee = period === 'all' ? Number(totals.platformCommission || gross - net) : gross * 0.15;
  const max = Math.max(...products.map((product) => product.gross), 1);
  const periodLabel = period === 'all' ? 'Todo el tiempo' : period === 'week' ? 'Últimos 7 días' : 'Últimos 30 días';

  return <div className="space-y-7"><section className="flex flex-col gap-4 rounded-3xl border border-white/70 bg-white/90 p-5 shadow-xl shadow-slate-200/40 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-slate-800">Resumen de ganancias</h2><p className="mt-1 text-xs text-slate-400">Consulta tus ventas brutas, descuentos y dinero neto.</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={() => setPeriod('all')} className={`rounded-xl px-3 py-2 text-xs font-bold ${period === 'all' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600'}`}>Todo</button><button onClick={() => setPeriod('week')} className={`rounded-xl px-3 py-2 text-xs font-bold ${period === 'week' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600'}`}>Semana</button><button onClick={() => setPeriod('month')} className={`rounded-xl px-3 py-2 text-xs font-bold ${period === 'month' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600'}`}>Mes</button><button onClick={onDownload} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white hover:bg-blue-700"><ArrowDownToLine className="h-4 w-4" /> CSV</button></div></section>
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Ventas brutas" value={money(gross)} detail={periodLabel} icon={CircleDollarSign} color="bg-blue-50 text-blue-600" /><Metric label="Descuento Apex" value={money(fee)} detail="Comisión del 15%" icon={Percent} color="bg-rose-50 text-rose-600" /><Metric label="Ganancia neta" value={money(net)} detail="Lo que recibes: 85%" icon={WalletCards} color="bg-emerald-50 text-emerald-600" /><Metric label="Ventas registradas" value={filteredOrders.length} detail="Pedidos del periodo" icon={ShoppingBag} color="bg-violet-50 text-violet-600" /></section>
    <section className="grid grid-cols-1 gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-white/70 bg-white/90 p-6 shadow-xl shadow-slate-200/40"><div className="mb-6 flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-lg font-bold text-slate-800"><Banknote className="h-5 w-5 text-blue-600" /> Ventas vs ganancia neta</h2><p className="mt-1 text-xs text-slate-400">Comparación por producto vendido</p></div><span className="text-xs text-slate-400">MXN</span></div><div className="space-y-5">{products.length === 0 ? <p className="py-10 text-center text-xs text-slate-400">No hay ventas para este periodo.</p> : products.slice(0, 8).map((product) => <div key={product.key}><div className="mb-2 flex justify-between gap-3 text-xs"><span className="max-w-[55%] truncate font-bold text-slate-700">{product.name}</span><span className="text-slate-500">Bruto {money(product.gross)} · Neto {money(product.net)}</span></div><div className="space-y-1"><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{ width: `${(product.gross / max) * 100}%` }} /></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${(product.net / max) * 100}%` }} /></div></div></div>)}</div><div className="mt-6 flex gap-5 border-t border-slate-100 pt-4 text-xs text-slate-500"><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-blue-500" />Ventas brutas</span><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-emerald-500" />Ganancia neta</span></div></div><div className="rounded-3xl border border-white/70 bg-white/90 p-6 shadow-xl shadow-slate-200/40"><div className="mb-6"><h2 className="flex items-center gap-2 text-lg font-bold text-slate-800"><CircleDollarSign className="h-5 w-5 text-emerald-600" /> Distribución de ingresos</h2><p className="mt-1 text-xs text-slate-400">Cómo se divide cada venta</p></div><div className="flex flex-col items-center gap-7 sm:flex-row sm:justify-center"><div className="relative h-44 w-44 rounded-full" style={{ background: 'conic-gradient(#10b981 0deg 306deg, #f43f5e 306deg 360deg)' }}><div className="absolute inset-7 flex items-center justify-center rounded-full bg-white text-center"><div><p className="text-xs text-slate-400">Neto</p><p className="font-bold text-emerald-600">85%</p></div></div></div><div className="space-y-4 text-sm"><div><p className="font-bold text-slate-700"><i className="mr-2 inline-block h-3 w-3 rounded-full bg-emerald-500" />Ganancia neta</p><p className="ml-5 text-xs text-slate-400">{money(net)}</p></div><div><p className="font-bold text-slate-700"><i className="mr-2 inline-block h-3 w-3 rounded-full bg-rose-500" />Comisión Apex</p><p className="ml-5 text-xs text-slate-400">{money(fee)}</p></div></div></div></div></section>
    <section className="overflow-x-auto rounded-3xl border border-white/70 bg-white/90 p-6 shadow-xl shadow-slate-200/40"><h2 className="mb-5 flex items-center gap-2 text-lg font-bold text-slate-800"><ShoppingBag className="h-5 w-5 text-blue-600" /> Ganancia por producto vendido</h2><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-slate-400"><th className="pb-3">Producto</th><th className="pb-3">Unidades</th><th className="pb-3">Venta bruta</th><th className="pb-3">Descuento 15%</th><th className="pb-3">Ganancia neta</th></tr></thead><tbody>{products.map((product) => <tr key={product.key} className="border-b border-slate-50 text-slate-700"><td className="py-4 font-bold">{product.name}</td><td className="py-4">{product.units}</td><td className="py-4">{money(product.gross)}</td><td className="py-4 text-rose-600">-{money(product.fee)}</td><td className="py-4 font-bold text-emerald-700">{money(product.net)}</td></tr>)}</tbody></table>{products.length === 0 && <p className="py-10 text-center text-xs text-slate-400">No hay productos vendidos para este periodo.</p>}</section>
    <section className="overflow-x-auto rounded-3xl border border-white/70 bg-white/90 p-6 shadow-xl shadow-slate-200/40"><h2 className="mb-5 flex items-center gap-2 text-lg font-bold text-slate-800"><Clock3 className="h-5 w-5 text-amber-600" /> Estado de tus ganancias</h2><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-amber-50 p-4"><p className="text-xs text-amber-700">Retenido</p><p className="mt-1 text-lg font-bold text-amber-800">{money(report?.sellers?.[0]?.held)}</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs text-emerald-700">Liberado</p><p className="mt-1 text-lg font-bold text-emerald-800">{money(report?.sellers?.[0]?.paid)}</p></div><div className="rounded-2xl bg-slate-100 p-4"><p className="text-xs text-slate-600">Comisión aplicada</p><p className="mt-1 text-lg font-bold text-slate-800">15%</p></div></div></section>
  </div>;
}
