'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Send, ShieldCheck } from 'lucide-react'
import { useAuth } from '@/context/AuthContext'

const initial = { full_name: '', curp: '', rfc: '', phone: '', birth_date: '', id_type: 'INE', id_number: '', address: '', city: '', state: '', postal_code: '', country: 'México', notes: '' }
const fields = [['full_name', 'Nombre completo', true], ['curp', 'CURP', true], ['rfc', 'RFC', false], ['phone', 'Teléfono', true], ['birth_date', 'Fecha de nacimiento', false], ['id_number', 'Número de identificación oficial', false], ['address', 'Domicilio completo', true], ['city', 'Ciudad', true], ['state', 'Estado', true], ['postal_code', 'Código postal', true]]

export default function SellerApplicationPage() {
  const router = useRouter(); const { user, role, loading: authLoading } = useAuth(); const [form, setForm] = useState(initial); const [status, setStatus] = useState(null); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!authLoading && !user) router.replace('/login') }, [user, authLoading, router])
  const submit = async (event) => { event.preventDefault(); setSaving(true); setStatus(null); const response = await fetch('/api/seller-applications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); setSaving(false); if (!response.ok) return setStatus({ type: 'error', text: result.error || 'No se pudo enviar' }); setStatus({ type: 'success', text: 'Solicitud enviada. El administrador revisará tus datos.' }); setTimeout(() => router.push('/perfil'), 1800) }
  return <main className="min-h-screen bg-slate-50 px-5 py-10"><div className="max-w-3xl mx-auto"><Link href="/convertirse-vendedor" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900"><ArrowLeft className="w-4 h-4" /> Volver a beneficios</Link><div className="mt-7 bg-white rounded-3xl border border-slate-200 shadow-sm p-6 md:p-10"><div className="flex gap-4 items-start"><div className="p-3 rounded-2xl bg-amber-100 text-amber-700"><ShieldCheck /></div><div><h1 className="text-3xl font-bold text-slate-900">Solicitud de vendedor</h1><p className="mt-2 text-sm text-slate-500">Usaremos esta información únicamente para validar tu identidad y prevenir fraudes.</p></div></div>{role && role !== 'cliente' ? <p className="mt-8 rounded-xl bg-amber-50 text-amber-700 px-4 py-3 text-sm">Tu cuenta ya no puede enviar esta solicitud.</p> : <form onSubmit={submit} className="mt-9 space-y-7"><div><h2 className="font-bold text-slate-900 mb-4">Datos personales</h2><div className="grid md:grid-cols-2 gap-4">{fields.slice(0, 6).map(([name, label, required]) => <label key={name} className="text-sm font-semibold text-slate-700">{label}{required && ' *'}<input required={required} type={name === 'birth_date' ? 'date' : 'text'} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-amber-400" /></label>)}</div></div><div><h2 className="font-bold text-slate-900 mb-4">Domicilio</h2><div className="grid md:grid-cols-2 gap-4">{fields.slice(6).map(([name, label, required]) => <label key={name} className="text-sm font-semibold text-slate-700">{label}{required && ' *'}<input required={required} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-amber-400" /></label>)}</div></div><label className="block text-sm font-semibold text-slate-700">Información adicional<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} rows={4} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-amber-400" placeholder="Cuéntanos brevemente qué tipo de productos venderás (opcional)" /></label>{status && <p className={`rounded-xl px-4 py-3 text-sm ${status.type === 'success' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{status.text}</p>}<button disabled={saving} className="inline-flex items-center gap-2 bg-[#162536] text-white px-6 py-3 rounded-xl font-bold text-sm disabled:opacity-50"><Send className="w-4 h-4" />{saving ? 'Enviando...' : 'Enviar solicitud'}</button></form>}</div></div></main>
}
